export const basic = [
  { hiragana: "あ", romaji: "a" },
  { hiragana: "い", romaji: "i" },
  { hiragana: "う", romaji: "u" },
  { hiragana: "え", romaji: "e" },
  { hiragana: "お", romaji: "o" },
  { hiragana: "か", romaji: "ka" },
  { hiragana: "き", romaji: "ki" },
  { hiragana: "く", romaji: "ku" },
  { hiragana: "け", romaji: "ke" },
  { hiragana: "こ", romaji: "ko" },
  { hiragana: "さ", romaji: "sa" },
  { hiragana: "し", romaji: "shi" },
  { hiragana: "す", romaji: "su" },
  { hiragana: "せ", romaji: "se" },
  { hiragana: "そ", romaji: "so" },
  { hiragana: "た", romaji: "ta" },
  { hiragana: "ち", romaji: "chi" },
  { hiragana: "つ", romaji: "tsu" },
  { hiragana: "て", romaji: "te" },
  { hiragana: "と", romaji: "to" },
  { hiragana: "な", romaji: "na" },
  { hiragana: "に", romaji: "ni" },
  { hiragana: "ぬ", romaji: "nu" },
  { hiragana: "ね", romaji: "ne" },
  { hiragana: "の", romaji: "no" },
  { hiragana: "は", romaji: "ha" },
  { hiragana: "ひ", romaji: "hi" },
  { hiragana: "ふ", romaji: "fu" },
  { hiragana: "へ", romaji: "he" },
  { hiragana: "ほ", romaji: "ho" },
  { hiragana: "ま", romaji: "ma" },
  { hiragana: "み", romaji: "mi" },
  { hiragana: "む", romaji: "mu" },
  { hiragana: "め", romaji: "me" },
  { hiragana: "も", romaji: "mo" },
  { hiragana: "や", romaji: "ya" },
  { hiragana: "", romaji: "" },
  { hiragana: "ゆ", romaji: "yu" },
  { hiragana: "", romaji: "" },
  { hiragana: "よ", romaji: "yo" },
  { hiragana: "ら", romaji: "ra" },
  { hiragana: "り", romaji: "ri" },
  { hiragana: "る", romaji: "ru" },
  { hiragana: "れ", romaji: "re" },
  { hiragana: "ろ", romaji: "ro" },
  { hiragana: "わ", romaji: "wa" },
  { hiragana: "", romaji: "" },
  { hiragana: "", romaji: "" },
  { hiragana: "", romaji: "" },
  { hiragana: "を", romaji: "wo" },
  { hiragana: "ん", romaji: "n" },
  { hiragana: "", romaji: "" },
  { hiragana: "", romaji: "" },
  { hiragana: "", romaji: "" },
  { hiragana: "", romaji: "" },
];

export const dakuten = [
  { hiragana: "が", romaji: "ga" },
  { hiragana: "ぎ", romaji: "gi" },
  { hiragana: "ぐ", romaji: "gu" },
  { hiragana: "げ", romaji: "ge" },
  { hiragana: "ご", romaji: "go" },
  { hiragana: "ざ", romaji: "za" },
  { hiragana: "じ", romaji: "ji" },
  { hiragana: "ず", romaji: "zu" },
  { hiragana: "ぜ", romaji: "ze" },
  { hiragana: "ぞ", romaji: "zo" },
  { hiragana: "だ", romaji: "da" },
  { hiragana: "ぢ", romaji: "ji" }, // Note: 'ぢ' is pronounced 'ji' but is written as 'di'
  { hiragana: "づ", romaji: "zu" }, // Note: 'づ' is pronounced 'zu' but is written as 'du'
  { hiragana: "で", romaji: "de" },
  { hiragana: "ど", romaji: "do" },
  { hiragana: "ば", romaji: "ba" },
  { hiragana: "び", romaji: "bi" },
  { hiragana: "ぶ", romaji: "bu" },
  { hiragana: "べ", romaji: "be" },
  { hiragana: "ぼ", romaji: "bo" },
  { hiragana: "ぱ", romaji: "pa" },
  { hiragana: "ぴ", romaji: "pi" },
  { hiragana: "ぷ", romaji: "pu" },
  { hiragana: "ぺ", romaji: "pe" },
  { hiragana: "ぽ", romaji: "po" },
];

export const combination = [
  { hiragana: "きゃ", romaji: "kya" },
  { hiragana: "", romaji: "" },
  { hiragana: "きゅ", romaji: "kyu" },
  { hiragana: "", romaji: "" },
  { hiragana: "きょ", romaji: "kyo" },

  { hiragana: "しゃ", romaji: "sha" },
  { hiragana: "", romaji: "" },
  { hiragana: "しゅ", romaji: "shu" },
  { hiragana: "", romaji: "" },
  { hiragana: "しょ", romaji: "sho" },

  { hiragana: "ちゃ", romaji: "cha" },
  { hiragana: "", romaji: "" },
  { hiragana: "ちゅ", romaji: "chu" },
  { hiragana: "", romaji: "" },
  { hiragana: "ちょ", romaji: "cho" },

  { hiragana: "にゃ", romaji: "nya" },
  { hiragana: "", romaji: "" },
  { hiragana: "にゅ", romaji: "nyu" },
  { hiragana: "", romaji: "" },
  { hiragana: "にょ", romaji: "nyo" },

  { hiragana: "ひゃ", romaji: "hya" },
  { hiragana: "", romaji: "" },
  { hiragana: "ひゅ", romaji: "hyu" },
  { hiragana: "", romaji: "" },
  { hiragana: "ひょ", romaji: "hyo" },

  { hiragana: "みゃ", romaji: "mya" },
  { hiragana: "", romaji: "" },
  { hiragana: "みゅ", romaji: "myu" },
  { hiragana: "", romaji: "" },
  { hiragana: "みょ", romaji: "myo" },
  { hiragana: "りゃ", romaji: "rya" },
  { hiragana: "", romaji: "" },
  { hiragana: "りゅ", romaji: "ryu" },
  { hiragana: "", romaji: "" },
  { hiragana: "りょ", romaji: "ryo" },
  { hiragana: "ぎゃ", romaji: "gya" },
  { hiragana: "", romaji: "" },
  { hiragana: "ぎゅ", romaji: "gyu" },
  { hiragana: "", romaji: "" },
  { hiragana: "ぎょ", romaji: "gyo" },
  { hiragana: "じゃ", romaji: "ja" },
  { hiragana: "", romaji: "" },
  { hiragana: "じゅ", romaji: "ju" },
  { hiragana: "", romaji: "" },
  { hiragana: "じょ", romaji: "jo" },
  { hiragana: "びゃ", romaji: "bya" },
  { hiragana: "", romaji: "" },
  { hiragana: "びゅ", romaji: "byu" },
  { hiragana: "", romaji: "" },
  { hiragana: "びょ", romaji: "byo" },
  { hiragana: "ぴゃ", romaji: "pya" },
  { hiragana: "", romaji: "" },
  { hiragana: "ぴゅ", romaji: "pyu" },
  { hiragana: "", romaji: "" },
  { hiragana: "ぴょ", romaji: "pyo" },
];

export const long = [
  { hiragana: "っか", romaji: "kka" },
  { hiragana: "っき", romaji: "kki" },
  { hiragana: "っく", romaji: "kku" },
  { hiragana: "っけ", romaji: "kke" },
  { hiragana: "っこ", romaji: "kko" },
  { hiragana: "っさ", romaji: "ssa" },
  { hiragana: "っし", romaji: "sshi" },
  { hiragana: "っす", romaji: "ssu" },
  { hiragana: "っせ", romaji: "sse" },
  { hiragana: "っそ", romaji: "sso" },
  { hiragana: "った", romaji: "tta" },
  { hiragana: "っち", romaji: "cchi" }, // Note: 'っち' is pronounced 'cchi' but is romanized as 'tchi'
  { hiragana: "っつ", romaji: "ttsu" }, // Note: 'っつ' is pronounced 'ttsu' but is romanized as 'ttsu'
  { hiragana: "って", romaji: "tte" },
  { hiragana: "っと", romaji: "tto" },
  { hiragana: "っな", romaji: "nna" },
  { hiragana: "っに", romaji: "nni" },
  { hiragana: "っぬ", romaji: "nnu" },
  { hiragana: "っね", romaji: "nne" },
  { hiragana: "っの", romaji: "nno" },
  { hiragana: "っは", romaji: "hha" },
  { hiragana: "っひ", romaji: "hhi" },
  { hiragana: "っふ", romaji: "ffu" }, // Note: 'っふ' is pronounced 'ffu' but is romanized as 'ffu'
  { hiragana: "っへ", romaji: "hhe" },
  { hiragana: "っほ", romaji: "hho" },
  { hiragana: "っま", romaji: "mma" },
  { hiragana: "っみ", romaji: "mmi" },
  { hiragana: "っむ", romaji: "mmu" },
  { hiragana: "っめ", romaji: "mme" },
  { hiragana: "っも", romaji: "mmo" },
  { hiragana: "っや", romaji: "yya" },
  { hiragana: "", romaji: "" },
  { hiragana: "っゆ", romaji: "yyu" },
  { hiragana: "", romaji: "" },
  { hiragana: "っよ", romaji: "yyo" },
  { hiragana: "っら", romaji: "rra" },
  { hiragana: "っり", romaji: "rri" },
  { hiragana: "っる", romaji: "rru" },
  { hiragana: "っれ", romaji: "rre" },
  { hiragana: "っろ", romaji: "rro" },
  { hiragana: "っわ", romaji: "wwa" },
  { hiragana: "", romaji: "" },
  { hiragana: "", romaji: "" },
  { hiragana: "", romaji: "" },
  { hiragana: "っを", romaji: "wwo" },
  { hiragana: "っん", romaji: "nn" },
  { hiragana: "", romaji: "" },
  { hiragana: "", romaji: "" },
  { hiragana: "", romaji: "" },
  { hiragana: "", romaji: "" },
];
