import type { Kanji } from "./kanji";

export const numbers: Kanji[] = [
    { kanji: "一", meaning: "one", hiragana: "いち" },
    { kanji: "二", meaning: "two", hiragana: "に" },
    { kanji: "三", meaning: "three", hiragana: "さん" },
    { kanji: "四", meaning: "four", hiragana: "よん" },
    { kanji: "五", meaning: "five", hiragana: "ご" },
    { kanji: "六", meaning: "six", hiragana: "ろく" },
    { kanji: "七", meaning: "seven", hiragana: "なな" },
    { kanji: "八", meaning: "eight", hiragana: "はち" },
    { kanji: "九", meaning: "nine", hiragana: "きゅう" },
    { kanji: "十", meaning: "ten", hiragana: "じゅう" },
    { kanji: "二十", meaning: "twenty", hiragana: "にじゅう" },
    { kanji: "三十", meaning: "thirty", hiragana: "さんじゅう" },
    { kanji: "四十", meaning: "forty", hiragana: "しじゅう" },
    { kanji: "五十", meaning: "fifty", hiragana: "ごじゅう" },
    { kanji: "六十", meaning: "sixty", hiragana: "ろくじゅう" },
    { kanji: "七十", meaning: "seventy", hiragana: "しちじゅう" },
    { kanji: "八十", meaning: "eighty", hiragana: "はちじゅう" },
    { kanji: "九十", meaning: "ninety", hiragana: "きゅうじゅう" },
    { kanji: "百", meaning: "hundred", hiragana: "ひゃく" },
    { kanji: "二百", meaning: "two hundred", hiragana: "にひゃく" },
    { kanji: "三百", meaning: "three hundred", hiragana: "さんびゃく" },
    { kanji: "四百", meaning: "four hundred", hiragana: "よんひゃく" },
    { kanji: "五百", meaning: "five hundred", hiragana: "ごひゃく" },
    { kanji: "六百", meaning: "six hundred", hiragana: "ろっぴゃく" },
    { kanji: "七百", meaning: "seven hundred", hiragana: "ななひゃく" },
    { kanji: "八百", meaning: "eight hundred", hiragana: "はっぴゃく" },
    { kanji: "九百", meaning: "nine hundred", hiragana: "きゅうひゃく" },
    { kanji: "千", meaning: "thousand", hiragana: "せん" },
    { kanji: "二千", meaning: "two thousand", hiragana: "にせん" },
    { kanji: "三千", meaning: "three thousand", hiragana: "さんぜん" },
    { kanji: "四千", meaning: "four thousand", hiragana: "よんせん" },
    { kanji: "五千", meaning: "five thousand", hiragana: "ごせん" },
    { kanji: "六千", meaning: "six thousand", hiragana: "ろくせん" },
    { kanji: "七千", meaning: "seven thousand", hiragana: "ななせん" },
    { kanji: "八千", meaning: "eight thousand", hiragana: "はっせん" },
    { kanji: "九千", meaning: "nine thousand", hiragana: "きゅうせん" },
    { kanji: "一万", meaning: "ten thousand", hiragana: "いちまん" },
    { kanji: "二万", meaning: "twenty thousand", hiragana: "にまん" },
    { kanji: "三万", meaning: "thirty thousand", hiragana: "さんまん" },
    { kanji: "四万", meaning: "forty thousand", hiragana: "よんまん" },
    { kanji: "五万", meaning: "fifty thousand", hiragana: "ごまん" },
    { kanji: "六万", meaning: "sixty thousand", hiragana: "ろくまん" },
    { kanji: "七万", meaning: "seventy thousand", hiragana: "ななまん" },
    { kanji: "八万", meaning: "eighty thousand", hiragana: "はちまん" },
    { kanji: "九万", meaning: "ninety thousand", hiragana: "きゅうまん" }
];
